version: '2'

services:
  dashboard:
    build: ./kit_dashboard
    volumes:
      - ./kit_dashboard:/usr/src/kit_dashboard
    ports:
      - '8000:8000'
    command: 'npm run start-local'

  api:
    build: ./kit_api
    volumes:
      - ./kit_api:/usr/src/kit_api
    ports:
      - '5000:5000'
    command: 'npm run start-local'

  postgres:
    image: postgres:9.5.4
    environment:
      POSTGRES_DB: kit
      POSTGRES_USER: kit
      POSTGRES_PASSWORD: community
    ports:
      - '5432:5432'
