version: '2'

services:
  dashboard:
    build: ./kit_dashboard
    volumes:
      - ./kit_dashboard:/usr/src/kit_dashboard
    ports:
      - '8000:8000'
    command: 'npm run start-local'

  api:
    build: ./kit_api
    volumes:
      - ./kit_api:/usr/src/kit_api
    ports:
      - '5000:5000'
    command: 'npm run start-local'

  chat:
    build: ./kit_chat
    volumes:
      - ./kit_chat:/usr/src/kit_chat
    ports:
      - '3000:3000'
    command: 'npm start'
  postgres:
    image: postgres:9.6.2
    environment:
      POSTGRES_DB: kit
      POSTGRES_USER: kit
      POSTGRES_PASSWORD: community
    ports:
      - '5432:5432'
  rabbitmq: 
    image: rabbitmq:3.6-management
    hostname: kit-rabbit
    ports: 
      - '5672:5672'
      - '15672:15672'